jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        # https://github.com/actions/checkout/tree/v3.0.2
        uses: actions/checkout@v3
      - name: Modify date and time
        run: |
          date > README.md
          cat README.md
      - name: Push to repository
        run: |
          git config --global user.name "piupiuisland"
          git config --global user.email "zhaodoudou233666@gmail.com"
          now=$(date)
          git add -A
          git commit -m "Auto Push on $now"
          git push